### ISSUE TITLE
Jittering display with wifi enabled

### ISSUE THREAD

**Issue by SCUBA82** [smartpanle/PanelLan_esp32_arduino#1]
Hello, 
first at all thank you for this library. It made my first steps with my ZX7D00CE01S realy easy. 
Unfortunatley I have issue when I've wifi activated on the esp32. The content on the screens jitters around and I have artefacts all over the place. 

However, I found out that the display runs totaly stable (with wifi enabled) when lowering the clock frequency from 24000000 to 16000000. 

I would love to see an option to modify the value of #define PanelLan_RGB_CLK_FREQ from outside of the library so my project can rely on the standard library and I don't have to alter the value directly in the library. 

br

**Comment by EeeeBin** [comment]
hi. SCUBA82
In the standard esp32-arduino-lib, the rgb screen will drift when turning on wifi. This problem can be solved by modifying esp32-arduino-lib.
pls try this: https://github.com/esp-arduino-libs/arduino-esp32-sdk/tree/high_perf

**Comment by vicelikedust** [comment]
That link is no longer active
