### ISSUE TITLE
Black screen with SC05

### ISSUE THREAD

**Issue by SuperJerry69** [smartpanle/PanelLan_esp32_arduino#18]
I went down to esp version 2.0.11, I tried to put in sc05.cpp #define PanelLan_SCREEN_WIDTH 320 (and 240 in height and vice versa instead of the initial 800x480) without success ... I use Arduino ver 2.3.3: is this the problem? My board is ZX2D80CEC22COF-AIO

**Comment by EeeeBin** [comment]
Hi,  SuperJerry69
Sorry, the current code does lack support for ZX2D80CEC22COF, and plans to add it in the next two days

**Comment by SuperJerry69** [comment]
Thanks !!! This is very good news for me, I tried to modify the library but I am far from being an expert :-( Good luck !   Jerome

**Comment by EeeeBin** [comment]
Hi, SuperJerry69
SC05_PLUS Support has been added: https://github.com/smartpanle/PanelLan_esp32_arduino/commit/8782378c5faff10ec3919d78caac9f17fc36611d

**Comment by SuperJerry69** [comment]
great! the graph works.
well I can't get the touch part to work (with the touch test example) :-(
![SC05_PLUS](https://github.com/user-attachments/assets/483d8e08-5dab-4d1f-9b4d-bba7b784eac0)

**Comment by EeeeBin** [comment]
Touch now works fine :)
fixed: 58cce8eabd530501aa3450387e80f9cab1f91b63

**Comment by SuperJerry69** [comment]
Nice ! Perfect !
![SC05_PLUS](https://github.com/user-attachments/assets/59c6459d-e2c4-4151-80ac-886becb99f65)
