### ISSUE TITLE
black screen after trying diferent examples

### ISSUE THREAD

**Issue by bderkk** [smartpanle/PanelLan_esp32_arduino#2]
Hi! I’m trying to work with this display but I’m having some issues. The problem is I can upload the code and print different thing with serial.print,. But I can not see anything in the display. I’ve tried also with different exemplars from the repo for this board and display. But I don’t know if I’ve to change anything on the board setup. The model is v14 wt32-sc01 plus.

**Comment by EeeeBin** [comment]
Hi, bderkk
Is there a configuration board? ESP32S3 Dev Module + 8MB QIO 80MHz + QSPI PSRAM

**Comment by bderkk** [comment]
Yes, I'm using arduino ide v2 latest version. And also esp32 boards alpha version (3.x). Could be this the problem?

**Comment by EeeeBin** [comment]
It may be due to the influence of **esp32 boards alpha version (3.x)**. I have not verified it on version 3.x. The current version is **esp32 2.0.11**.

**Comment by bderkk** [comment]
I will try with that version and tell you something!

Thank you so much!

**Comment by bderkk** [comment]
Okay, with version 2.0.11 is working. The problem was version 3.x

Thank you so much!
