### ISSUE TITLE
BOARD_SC02 / ZX4D30NE01S-V15 example hello_world does not work

### ISSUE THREAD

**Issue by erazor83** [smartpanle/PanelLan_esp32_arduino#3]
Not much to say.

Can anyone confirm the current library works with this module?

`
PanelLan tft(BOARD_SC02);
`

**Comment by EeeeBin** [comment]
Hi. eraz0r83
I just tested that sc02 is working normally

Please confirm whether the board configuration is correct
arduino esp32 boards v2.0.13
ESP32S3 Dev Module | 16MB QIO 80MHz | OPI PSRAM

**Comment by erazor83** [comment]
Thanks a lot!
I was using the wrong board setup.
It works with your settings.
