### ISSUE TITLE
LVGL support? 

### ISSUE THREAD

**Issue by xXhoobaXx** [smartpanle/PanelLan_esp32_arduino#6]
The library is amazing and works perfectly 
Can you help me to use it with LVGL 

The screen I am using is the "SC05"	
ZX7D00CE01S

I am using Arduino IDE 
Or platform IO if that works

**Comment by EeeeBin** [comment]
Try test this: https://github.com/smartpanle/PanelLan_esp32_arduino/issues/4#issuecomment-1996316186

**Comment by xXhoobaXx** [comment]
I just used the .zip folder you mentioned 
This is the results https://github.com/user-attachments/assets/33911200-5e2a-4601-912d-7fe2f94567ef

**Comment by EeeeBin** [comment]
Sorry, we have reproduced the same problem and are trying to fix it now. It will take some time.

**Comment by xXhoobaXx** [comment]
thank you i appreciate the help, i'll wait for your reply

**Comment by gpena208777** [comment]
Did you have boot loop issues?

**Comment by xXhoobaXx** [comment]
can you be a bit specific or share your code/settings 
for me that usually happens if I have the wrong board settings or code wrong memory allocation

**Comment by EeeeBin** [comment]
Hi. 
We have found the problem. It is caused by insufficient PSRAM bandwidth. It is not easy to fix in Arduino. We are still trying to see if it can be fixed. 
You can try to use ESP-IDF for development. https://github.com/smartpanle/QMSD-ESP32-BSP has an integrated lvgl driver

**Comment by EeeeBin** [comment]
You can try the following method. I tested that the screen is normal.
1. setting this to 20Mhz -> https://github.com/smartpanle/PanelLan_esp32_arduino/blob/master/src/board/sc05/sc05.cpp#L19
2. Follow the prompts to use 3.0.2-h (3.0.3 has not been tested to see if it can be used) https://github.com/smartpanle/PanelLan_esp32_arduino/blob/master/src/board/sc05/sc05.cpp#L19

**Comment by xXhoobaXx** [comment]
thank you i can confirm that Arduino-ide worked, I'll do more testing for platform-io and esp-idf later
quick question: what's the recommended partition scheme option for the device?

**Comment by EeeeBin** [comment]
Custom, generally, with a 800x480 screen and lvgl, the app size will exceed 4M, FATFS is useless and not suitable for storing UI materials
